name: pdf-processor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=23.0
  - flask=2.3.2
  - flask-cors=3.0.10
  - werkzeug=2.3.4
  - pymupdf=1.21.1
  - langchain=0.0.267
  - faiss-cpu=1.7.4
  - pip:
    - langchain-ollama==0.0.1
    - python-dotenv==1.0.0
    - streamlit==1.32.0
    - PyPDF2==3.0.1
    - openai==1.12.0
    - uuid==1.30
    - difflib==0.1
